import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" style={{ height: '100%' }}>
      <body suppressHydrationWarning={true} style={{ height: '100%', margin: 0 }}>
        {children}
        <div className={'quote'}>
          "Минимализм в интерфейсе — ключ к сердцу пользователя, открывающий двери в мир понимания и легкости
          взаимодействия." © ChatGPT
        </div>
      </body>
    </html>
  );
}
