import type { Metadata } from 'next';
import './globals.css';
import NextAuthProvider from '@/app/auth-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <NextAuthProvider>{children}</NextAuthProvider>
        <div className={'quote'}>
          &quot;Минимализм в интерфейсе — ключ к сердцу пользователя, открывающий двери в мир понимания и легкости
          взаимодействия.&quot; © ChatGPT
        </div>
      </body>
    </html>
  );
}
